#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

//require_once 'app/App.php';

use Cliclicli\App\App;

$app = new App($argv);
$app->start();